<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Revit_All_Main_Versions_API_x64" Version="2019.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AllInOneMEP.Core\AllInOneMEP.Core.csproj" />
    <ProjectReference Include="..\AllInOneMEP.UI\AllInOneMEP.UI.csproj" />
  </ItemGroup>
</Project>
